### ISSUE TITLE
help error(dont have coding idea)

### ISSUE THREAD

**Issue by dev-adalz** [Solseum/solseum-nft-generator#17]
```RANDOMIZE OUTPUT ACTIVE... NFTs LOCATION WILL BE SHUFFLED BEFORE THE METADATA+PNG IS GENERATED.
THE MEANING OF THIS IS: YOUR 0.json THAT SHOULD BE NFT #0, CAN BE THE NFT #1234 AND SO ON.

Cleaning output folder... Done.
Obtainig attributes list and order of layers... Done.
Obtaining Bg items and creating the tombola... Traceback (most recent call last):
  File "C:\Users\adalz\solseum-nft-generator\main.py", line 28, in <module>
    nfts = NftCreator(numberNFTs, folderPaths, testRarities, randomizedOutput)
  File "C:\Users\adalz\solseum-nft-generator\includes\nft_creator.py", line 19, in __init__
    self.items, self.itemsPath, self.itemsTombola, self.maxPossibilities 
= self.GetItemsList(self.orderedLayersPath,self.attributes)
  File "C:\Users\adalz\solseum-nft-generator\includes\nft_creator.py", line 93, in GetItemsList
    item, itemPath, itemTombola = self.GetItemsPerAttribute(attributesPath[i], attributes[i])
  File "C:\Users\adalz\solseum-nft-generator\includes\nft_creator.py", line 116, in GetItemsPerAttribute
    item.append(file[1].replace('.png', '').replace('_', ' ').title())   
IndexError: list index out of range```

**Comment by Solseum** [comment]
You dont have the correct format in ur images! Some of ur Bg or more doesnt meet the number-name.png

For example 5-cyan.png
