### ISSUE TITLE
OSError: image file is truncated

### ISSUE THREAD

**Issue by DmytroCrawford** [Solseum/solseum-nft-generator#5]
Error below

"File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/ImageFile.py", line 237, in load
    s = read(self.decodermaxblock)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 896, in load_read
    cid, pos, length = self.png.read()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 162, in read
    length = i32(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/_binary.py", line 75, in i32be
    return unpack_from(">I", c, o)[0]
struct.error: unpack_from requires a buffer of at least 4 bytes for unpacking 4 bytes at offset 0 (actual buffer size is 0)"

**Comment by Solseum** [comment]
What Operative system are you using?

**Comment by DmytroCrawford** [comment]
Macbook Air M1 Chip - Mac OS

**Comment by DmytroCrawford** [comment]
> Macbook Air M1 Chip - Mac OS

I have done a gen before, this just started this time around

**Comment by Solseum** [comment]
Mmm thats the full error? Because doesnt show any line in our code, just an error in PIL Library

**Comment by DmytroCrawford** [comment]
> Error below
> 
> "File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/ImageFile.py", line 237, in load s = read(self.decodermaxblock) File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 896, in load_read cid, pos, length = self.png.read() File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 162, in read length = i32(s) File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/_binary.py", line 75, in i32be return unpack_from(">I", c, o)[0] struct.error: unpack_from requires a buffer of at least 4 bytes for unpacking 4 bytes at offset 0 (actual buffer size is 0)"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dmytrocrawford/Desktop/Nft Stuff/solseum-nft-generator/main.py", line 28, in <module>
    nfts = NftCreator(numberNFTs, folderPaths, testRarities, randomizedOutput)
  File "/Users/dmytrocrawford/Desktop/Nft Stuff/solseum-nft-generator/includes/nft_creator.py", line 39, in __init__
    self.fMet, self.fDNA = self.CreateImageAndMetadata(i, self.nftsQuantity[i], folder_paths[i])
  File "/Users/dmytrocrawford/Desktop/Nft Stuff/solseum-nft-generator/includes/nft_creator.py", line 214, in CreateImageAndMetadata
    nft.CreateImage()
  File "/Users/dmytrocrawford/Desktop/Nft Stuff/solseum-nft-generator/includes/nft.py", line 24, in CreateImage
    frontLayer = frontLayer.convert('RGBA')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/Image.py", line 915, in convert
    self.load()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/ImageFile.py", line 243, in load
    raise OSError("image file is truncated") from e
OSError: image file is truncated

**Comment by Solseum** [comment]
Which type of image are you using? Png-32, jpeg?

**Comment by DmytroCrawford** [comment]
PNG

**Comment by Solseum** [comment]
Can you try with the example assets that comes with the github? Because I think is an issue with ur images :c

**Comment by DmytroCrawford** [comment]
Should I try to reformat my images?

**Comment by Solseum** [comment]
If the examples images that comes witht the default solseum generator works, is because your images are wrong

**Comment by DmytroCrawford** [comment]
The generator works for about 80 images then crashes

**Comment by DmytroCrawford** [comment]
The issue was one of my images. My apologise
